FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build-project
WORKDIR /app
COPY ./ ./
RUN dotnet restore
RUN dotnet publish -c Release -o /publish

#FROM mcr.microsoft.com/dotnet/core/runtime:3.1
#COPY --from=build-project /publish /publish
ENV ASPNETCORE_ENVIRONMENT=development
ENTRYPOINT dotnet /publish/BraintreeSample.API.dll
